"""create core schema

Revision ID: fab5aa54588b
Revises: 
Create Date: 2026-09-19 08:32:57.657791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fab5aa54588b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum('movie', 'book', 'tv', 'podcast', name='content_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('creator', sa.String(length=500), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(length=1000), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('feed_url', sa.String(length=1000), nullable=True),
    sa.Column('external_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('to_consume', 'done', name='status_enum'), server_default='to_consume', nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating IS NULL OR (rating BETWEEN 1 AND 10)', name='ck_items_rating_range'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_url'),
    sa.UniqueConstraint('imdb_id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_index(op.f('ix_items_content_type'), 'items', ['content_type'], unique=False)
    op.create_index('ix_items_status', 'items', ['status'], unique=False)
    op.create_table('item_platforms',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'platform_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_platforms')
    op.drop_index('ix_items_status', table_name='items')
    op.drop_index(op.f('ix_items_content_type'), table_name='items')
    op.drop_table('items')
    op.drop_table('platforms')
    op.drop_table('languages')
    # ### end Alembic commands ###
